#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse

from grasslib.configurator import Params
from grasslib.grasslib import GRASS

DEFAULT_CONFIG_NAME = 'logg_ranging.conf'


def parse_args():
    parser = argparse.ArgumentParser(description='Create Database for logging ranging.')

    parser.add_argument(
        '--config',
        dest='config',
        action='store',
        # const=DEFAULT_CONFIG_NAME,
        default=DEFAULT_CONFIG_NAME,
        help='Config file (default: %s)' % (DEFAULT_CONFIG_NAME, )
    )
    parser.add_argument(
        '--type',
        dest='type',
        action='store',
        choices = ['rast', 'vect'],
        required=True,
        help='Type of layer (rast/vect).'
    )
    parser.add_argument(
        '--pattern',
        dest='pattern',
        action='store',
        required=True,
        help='Pattern of layer name.'
    )
    args = parser.parse_args()

    return args


def main():
    args = parse_args()
    args = vars(args)

    type = args['type']
    pattern = args['pattern']

    config = args['config']
    config_params = Params(config)

    grass_lib = config_params.grass_lib
    grass_exec = config_params.grass_exec

    location = config_params.location
    dbase = config_params.grassdata

    grs = GRASS(
        gisexec=grass_exec,
        gisbase=grass_lib,
        grassdata=dbase,
        location=location,
        init_loc=True
    )

    maps = grs.grass.list_strings(type, pattern=pattern)
    print '\n'.join(maps)


if __name__ == '__main__':
    main()

